/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    HyperlaneIncreaseSupplyCaps: {
      address: "0x610178dA211FEF7D417bC0e6FeD39F05609AD788",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_mailbox",
              type: "address",
            },
            {
              internalType: "address",
              name: "_addr",
              type: "address",
            },
          ],
          name: "increaseSupplyCap",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
  421614: {
    LZeroIncreaseSupplyCaps: {
      address: "0x2947941CDe2447D1cA5Df91801Cc85B8B01cb89d",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_endpoint",
              type: "address",
            },
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
          ],
          name: "AddressEmptyCode",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "AddressInsufficientBalance",
          type: "error",
        },
        {
          inputs: [],
          name: "FailedInnerCall",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidDelegate",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidEndpointCall",
          type: "error",
        },
        {
          inputs: [],
          name: "LzTokenUnavailable",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "eid",
              type: "uint32",
            },
          ],
          name: "NoPeer",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "msgValue",
              type: "uint256",
            },
          ],
          name: "NotEnoughNative",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "eid",
              type: "uint32",
            },
            {
              internalType: "bytes32",
              name: "sender",
              type: "bytes32",
            },
          ],
          name: "OnlyPeer",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "SafeERC20FailedOperation",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint32",
              name: "eid",
              type: "uint32",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "peer",
              type: "bytes32",
            },
          ],
          name: "PeerSet",
          type: "event",
        },
        {
          inputs: [],
          name: "MAX_SUPPLY",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "addr",
              type: "address",
            },
          ],
          name: "addressToBytes32",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [],
          name: "endpoint",
          outputs: [
            {
              internalType: "contract ILayerZeroEndpointV2",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "peer",
              type: "address",
            },
          ],
          name: "increaseSupplyCap",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "oAppVersion",
          outputs: [
            {
              internalType: "uint64",
              name: "senderVersion",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "receiverVersion",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "eid",
              type: "uint32",
            },
          ],
          name: "peers",
          outputs: [
            {
              internalType: "bytes32",
              name: "peer",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_delegate",
              type: "address",
            },
          ],
          name: "setDelegate",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint32",
              name: "_eid",
              type: "uint32",
            },
            {
              internalType: "bytes32",
              name: "_peer",
              type: "bytes32",
            },
          ],
          name: "setPeer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "peer",
              type: "address",
            },
          ],
          name: "updatePeers",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        endpoint: "@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppSender.sol",
        oAppVersion:
          "@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppSender.sol",
        owner: "@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppSender.sol",
        peers: "@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppSender.sol",
        renounceOwnership:
          "@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppSender.sol",
        setDelegate:
          "@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppSender.sol",
        setPeer: "@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppSender.sol",
        transferOwnership:
          "@layerzerolabs/lz-evm-oapp-v2/contracts/oapp/OAppSender.sol",
      },
    },
  },
  534351: {
    HyperlaneIncreaseSupplyCaps: {
      address: "0x90Daa01277e6d0776294d27b3292516E00753d11",
      abi: [
        {
          inputs: [
            {
              internalType: "uint256",
              name: "message_id",
              type: "uint256",
            },
          ],
          name: "increaseSupplyCap",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
